import Head from 'next/head';

import { ViewUser } from '@/components/ViewUser';

export default function Home() {
  return (
    <>
      <Head>
        <title>My Pokemon Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ViewUser />
    </>
  );
}
