import Head from 'next/head';

import { STYLES } from '@/@redux/features';
import * as S from '@/@redux/store';
import { HomePage } from '@/containers/HomePage';
import { useWindowSize } from '@/hooks/useWindow';
import { useEffect } from 'react';

export default function Home() {
  const dispatch = S.useAppDispatch();
  const { windowSize } = useWindowSize();

  useEffect(() => {
    // if (windowSize.width === undefined || windowSize.width < 768) return;

    dispatch(STYLES.shrinkHomeButton(true));
    setTimeout(() => {
      dispatch(STYLES.shrinkHomeButton(false));
    }, 5000);
  }, [dispatch, windowSize.width]);

  return (
    <>
      <Head>
        <title>My Pokemon Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage />
    </>
  );
}
